/*
*********************************************************************************************************
*                                                uC/OS-II
*                                          The Real-Time Kernel
*
*                           (c) Copyright 1992-1999, Jean J. Labrosse, Weston, FL
*                                           All Rights Reserved
*
*                                           MASTER INCLUDE FILE
*********************************************************************************************************
*/

#include "../port/OS_CPU.H"
#include "../user/OS_CFG.H"
#include "uCOS_II.H"

#include "../port/GlobalDef.h"
#include <reg51.h>
